### ISSUE TITLE
Mobile Usability: Text too small to read

### ISSUE THREAD

**Issue by captn3m0** [hginit/hginit.github.io#1]
As reported by Google

> A significant portion of the text on the page is too small relative to the width of the page. This makes the text hard to read on a mobile device. Look at the test screenshot for your device to try to identify the problematic text.

> To fix: Specify a viewport for your web pages and set all your font sizes to scale properly within the viewport, so the text will be visible on a device screen. [Read more about best practices for font size](https://web.dev/font-size/).

As reported by [PageSpeed Insights](https://pagespeed.web.dev/report?url=https%3A%2F%2Fhginit.github.io%2F00.html)

> Font sizes less than 12px are too small to be legible and require mobile visitors to “pinch to zoom” in order to read. Strive to have >60% of page text ≥12px.

**Comment by elidakirigo** [comment]
hello!, I'd love to work on this issue if it's still open and un-assigned. thanks

**Comment by captn3m0** [comment]
Looks like this is already resolved with my recent fixes and font-switch.

![image](https://user-images.githubusercontent.com/584253/223378274-15eb4eb6-d27b-4e20-9f94-ec43d06da6ac.png)

Closing this.

**Comment by elidakirigo** [comment]
no problem.
