### ISSUE TITLE
Responsive Design: Page Contents

### ISSUE THREAD

**Issue by captn3m0** [hginit/hginit.github.io#14]
The page contents currently are not responsive, and require scrolling horizontally on mobile devices. Fixing this would include all the content on all the pages:

1. Intro text on pages.
2. Body content text
3. Images, which should be scaled to 100% width
4. Page Header Image and Heading

We already have some responsive design built with #4 and #5 for the menu and the home-nav.

**Comment by mantosh-mariner** [comment]
could you assign it to me ?

**Comment by captn3m0** [comment]
See [Do not ask maintainers to assign you an issue](https://forum.fossunited.org/t/advice-on-contributing-to-open-source-projects/4109/3)

> Do not ask maintainers to “assign an issue”. Specifically on GitHub/GitLab - assignment can only happen to existing maintainers, so maintainers can’t even do it. If you’re working on a specific issue, feel free to mention it, but only if you’re serious about it, and ideally have something to show (like a link to a branch with changes).

**Comment by captn3m0** [comment]
Resolved with #15, thanks to @kailoon 🥇
