### ISSUE TITLE
Accessibility: Image Alt Tags

### ISSUE THREAD

**Issue by captn3m0** [hginit/hginit.github.io#3]
Add alt tags explaining all of the images clearly in plain text. 

See https://web.dev/text-alternatives-for-images/

See https://github.com/hginit/hginit.github.io/search?q=img+src for list of images.

**Comment by Andrew-ezeani** [comment]
Hello, this will be my first open source contribution. Can I handle this?

**Comment by prasadj2003** [comment]
Is this up for grabs?
willing to work on it

**Comment by captn3m0** [comment]
Please don't ask questions like "is this up for grabs", or "can i pick this up" for trivial issues like this - just file a PR instead.  See https://kentcdodds.com/blog/becoming-an-open-source-project-maintainer for more details.

Note: Some of the content has been converted from html to markdown, so you should also search for `![` in the `*.md` files to ensure you get all of the images.

**Comment by captn3m0** [comment]
Current pending tags:

```
00.html
134:<p><img src="i/00-svn.png" alt="" /></p>

01.html
236:<p><img src="i/01-commit0.png" alt="" /></p>
276:<p><img src="i/01-commit1.png" alt="" /></p>
313:<p><img src="i/01-commit2.png" alt="" /></p>

02.html
106:<p><img src="i/02-web.png" alt="" /></p>
165:<p><img src="i/02-commit0.png" alt="" /></p>
219:<p><img src="i/02-repo-2.png" alt="" /></p>
267:<p><img src="i/02-repo-3.png" alt="" /></p>
275:<p><img src="i/02-web-2.png" alt="" /></p>
414:<p><img src="i/02-repo-4.png" alt="" /></p>
452:<p><img src="i/02-repo-5.png" alt="" /></p>
504:<p><img src="i/02-repo-6.png" alt="" /></p>
632:<p><img src="i/02-repo-7.png" alt="" /></p>

03.html
341:<p><img src="i/03-repo.png" alt="" /></p>
381:<p><img src="i/03-repo-2.png" alt="" /></p>
```
