### ISSUE TITLE
Responsive Design: Fix home navigation scroll

### ISSUE THREAD

**Issue by captn3m0** [hginit/hginit.github.io#4]
The scroll for the listing on the home page is not natural. It should instead be top-to-bottom on the homepage.

<img width="287" alt="image" src="https://user-images.githubusercontent.com/584253/214348974-d0ede8c4-654e-4293-ade1-ac4656cdce9e.png">

**Comment by elidakirigo** [comment]
hello!, I'd love to work on this issue if it's still open and un-assigned. thanks

**Comment by captn3m0** [comment]
Feel free to pick this up [^1]. My suggested solution would be to:

1. Create vertical variants of all homenav images
2. Write additional styles for devices with display width <1000px to switch the images to a vertical layout.

See this image for example:

![homenav-vertical-1](https://user-images.githubusercontent.com/584253/223395100-c5e78850-e68e-40bd-a072-b46bedd2fe05.png)

We do have sources for the original images, but they happen to be in an ancient CPT 9 format, which I can't open.

[^1]: General advice, for small issues like these is to avoid comments "claiming" the issue, and just file a PR instead.

**Comment by elidakirigo** [comment]
sure! i'll take a look

**Comment by jlduchaney** [comment]
Working on this for Hacktoberfest 2024!

**Comment by captn3m0** [comment]
If you need any help with image conversions, do reach out.

**Comment by jlduchaney** [comment]
Hi @captn3m0! Will you have time to review my pull requests before October 31? 

If you don't have the bandwidth, I completely understand. I would just like to know if this is the case, so I can pick a different repository to work on for Hacktoberfest. Thanks in advance!

**Comment by captn3m0** [comment]
Yes. 

Since there's only single-digit pages in the entire repo, they are quite easy to review for breaking changes and correctness. As long as you take care to avoid breaking the site, should be easy to merge.

**Comment by jlduchaney** [comment]
Thanks for the quick response. In that case, I'll continue working through the issues you've posted. Appreciate your time!

**Comment by jlduchaney** [comment]
Hi @captn3m0! I'm gently following up here. Please let me know if your availability has changed since your last comment. Thanks!

**Comment by captn3m0** [comment]
If it's a small PR, I'll definitely review it within a day.

**Comment by jlduchaney** [comment]
Thanks again for getting back to me so quickly. I have four open PRs, but they're all pretty small, so I don't think it should be a problem.

**Comment by jlduchaney** [comment]
Hi @captn3m0 ! Might you consider applying the "hacktoberfest-accepted" label to each of my four pull requests before end of day today? This way, they'll be eligible to qualify for Hacktoberfest even if you don't have time to merge them before midnight. Please let me know either way, and thanks again :blush:

**Comment by captn3m0** [comment]
I've merged the two content PRs, and applied the label on the other two (#10, #11). The diff seemed okay, but I want to review them locally once before merging.

Thanks for your contributions 🥇!

**Comment by jlduchaney** [comment]
Thanks for your quick response, as always! I'll set aside some time this weekend to figure out the .log files.

And thank you for being so welcoming. As someone who's still learning to code, having you as a maintainer made my first-ever Hacktoberfest a positive, approachable experience. I appreciate the work you're doing to keep hginit.com alive. Cheers!

**Comment by mantosh-mariner** [comment]
Hi, I would like to work on this issue. Could you assign it to me?

**Comment by captn3m0** [comment]
This is closed already with #10, but you can try #14 - since the page contents are still pending.

**Comment by mantosh-mariner** [comment]
> This is closed already with #10, but you can try #14 - since the page contents are still pending
yeah i'm ready to solve issue , you can assign to me issue  #14 now

**Comment by mantosh-mariner** [comment]
Hi @captn3m0, could you confirm the repository link for this issue #14 ? I'd like to contribute. Thank you!
